MAP_ATOM_SYMBOLS:
  H: 0
  C: 1
  N: 2
  O: 3
  F: 4
  P: 5
  S: 6
  Cl: 7
  Br: 8
  I: 9

MAP_HYBRIDIZATION:
  SP: 0
  SP2: 1
  SP3: 2
  SP3D: 3
  SP3D2: 4
  UNSPECIFIED: 5
  OTHER: 6

MAP_CHIRALITY:
  CHI_ALLENE: 0
  CHI_OCTAHEDRAL: 1
  CHI_OTHER: 2
  CHI_SQUAREPLANAR: 3
  CHI_TETRAHEDRAL: 4
  CHI_TETRAHEDRAL_CCW: 5
  CHI_TETRAHEDRAL_CW: 6
  CHI_TRIGONALBIPYRAMIDAL: 7
  CHI_UNSPECIFIED: 8

MAP_BOND_TYPES:
  UNSPECIFIED: 0
  SINGLE: 1
  DOUBLE: 2
  TRIPLE: 3
  QUADRUPLE: 4
  QUINTUPLE: 5
  HEXTUPLE: 6
  ONEANDAHALF: 7
  TWOANDAHALF: 8
  THREEANDAHALF: 9
  FOURANDAHALF: 10
  FIVEANDAHALF: 11
  AROMATIC: 12
  IONIC: 13
  HYDROGEN: 14
  THREECENTER: 15
  DATIVEONE: 16
  DATIVE: 17
  DATIVEL: 18
  DATIVER: 19
  OTHER: 20
  ZERO: 21